engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.py"
  - "**.sh"
exclude_paths:
- doc/**/*
- scripts/**/*
- kicad_mod/**/*
